name: Deploy SAMACK SHORTENER

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  # Job Único: Compilar e Publicar no GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código-Fonte
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências
        run: npm install

      - name: Compilar Frontend React
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          token: ${{ secrets.DEPLOY_TOKEN }}
